name: Test Action

on: [push]

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - name: check
              run: ls
            
            
            
            - name: Run Action
              uses: ./action
              with:
                python-version: 3.9
                miniconda-version: "latest"