name: Dry Run

on: [push]

permissions: write-all

env:
  CARGO_TERM_COLOR: always

jobs:
    test:
        runs-on: macos-13
        steps:
            - uses: actions/checkout@v3
            
            - name: Run Action
              uses: ./
              with:
                python-version: 3.12
                miniconda-version: "latest"
                replace: true