name: Dry Run

on: [push]

permissions: write-all

env:
  CARGO_TERM_COLOR: always

jobs:
    test:
        strategy:
          matrix:
            # os: [ubuntu-latest, macos-latest, windows-latest]
            os: [ubuntu-latest]

        runs-on: ${{ matrix.os }}
        steps:
            - uses: actions/checkout@v3
            
            - name: Run Action
              uses: ./
              with:
                python-version: 3.12
                miniconda-version: "latest"
                replace: yes