name: Test Action

on: [push]

jobs:
    test:
        runs-on: ubuntu-latest
        steps:

            - name: check
              run: pwd && ls
            
            - name: Run Action
              uses: ./action
              with:
                python-version: 3.9
                miniconda-version: "latest"